{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-frontend
type: Opaque
stringData:
  __APP_INJECTED_RUNTIME_CONFIG__: {{ .Values.appConfig | toJson | quote }}
{{- end }}